---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-monitoring
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: dotnet-monitoring
  template:
    metadata:
      labels:
        app: dotnet-monitoring
    spec:
      containers:
        - name: dotnet-monitoring
          image: shrutifarkya/dotnet-monitoring:${BUILD_NUMBER}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
